config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.book.body
    - node.type.book
  module:
    - book
    - bootstrap_layouts
    - layout_builder
    - layout_builder_restrictions
    - layout_library
    - text
    - user
third_party_settings:
  layout_builder:
    allow_custom: false
    enabled: true
    sections:
      -
        layout_id: bs_2col_stacked
        layout_settings:
          label: ''
          layout:
            wrapper: div
            classes:
              row: row
            add_layout_class: 1
            attributes: ''
          regions:
            top:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
            left:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            right:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            bottom:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
        components:
          1295a7be-f121-40dd-ab42-322a8a4922eb:
            uuid: 1295a7be-f121-40dd-ab42-322a8a4922eb
            region: left
            configuration:
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              id: 'field_block:node:book:body'
              formatter:
                label: hidden
                type: text_default
                settings: {  }
                third_party_settings: {  }
            additional: {  }
            weight: 0
          590ecf5d-9024-4b07-84ea-6cde1b2955d0:
            uuid: 590ecf5d-9024-4b07-84ea-6cde1b2955d0
            region: bottom
            configuration:
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              id: 'extra_field_block:node:book:links'
            additional: {  }
            weight: 0
          2faddfc4-5058-4d44-9c9d-973365d6b1c2:
            uuid: 2faddfc4-5058-4d44-9c9d-973365d6b1c2
            region: right
            configuration:
              id: book_navigation
              label: Sections
              provider: book
              label_display: visible
              block_mode: 'all pages'
              context_mapping: {  }
            additional: {  }
            weight: 0
        third_party_settings: {  }
  layout_library:
    enable: false
  layout_builder_restrictions:
    allowed_block_categories: {  }
    entity_view_mode_restriction:
      whitelisted_blocks: {  }
      blacklisted_blocks: {  }
      allowed_layouts: {  }
id: node.book.default
targetEntityType: node
bundle: book
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
  links:
    weight: 101
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  langcode: true
  search_api_excerpt: true
