hidden:
  langcode: true
  panelizer: true
third_party_settings:
  panelizer:
    enable: true
    custom: true
    displays:
      default:
        blocks:
          197a21c8-479d-4d6b-9a05-5eaaf82b0e0e:
            id: 'entity_field:node:body'
            label: Body
            provider: ctools_block
            label_display: '0'
            formatter:
              label: hidden
              type: text_default
              settings: {  }
              third_party_settings: {  }
              weight: 0
            region: content
            weight: 1
            context_mapping:
              entity: '@panelizer.entity_context:entity'
            uuid: 197a21c8-479d-4d6b-9a05-5eaaf82b0e0e
          588e477f-63e7-471a-b464-16a842b8abf3:
            id: page_title_block
            label: 'Page title'
            provider: core
            label_display: '0'
            region: content
            weight: 0
            uuid: 588e477f-63e7-471a-b464-16a842b8abf3
            context_mapping: {  }
          c795868d-d954-48e3-8c26-fc1155d2b92a:
            id: local_tasks_block
            label: Tabs
            provider: core
            label_display: '0'
            primary: true
            secondary: true
            region: content
            weight: 0
            uuid: c795868d-d954-48e3-8c26-fc1155d2b92a
            context_mapping: {  }
        id: panels_variant
        uuid: df0d1b37-8cd5-46d3-b900-f18df4825325
        label: ''
        weight: 0
        layout: layout_onecol
        layout_settings: {  }
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:page:default:default'
        builder: ipe
        static_context: {  }
